image: maven:3.6.1-jdk-11

before_script:
  - cd air
  - chmod +x mvnw

variables:
  SONAR_TOKEN: "$SONAR_TOKEN"

stages:
  - build
  - test
  - quality

compile:
  stage: build
  script: ./mvnw compile

mvn-test:
  stage: test
  script: ./mvnw test

sonar:
  stage: quality
  script:
    - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.qualitygate.wait=true